version: "2"

run:
  timeout: 5m

linters:
  default: standard
  disable:
    - depguard
  exclusions:
    rules:
      - linters: [errcheck]
        path: benchmark_test\.go

formatters:
  enable:
    - gofmt
    - goimports
